on: push
name: Lint

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: cargo clippy --fix --all-targets --all-features
      - name: Run rustfmt
        run: cargo fmt --all
      - name: Push changes
        run: git push origin ${{ github.ref }}
